# -*- coding: utf-8 -*-
"""fraud detection .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YZ1vQuw-sN_Ey__6IXfs4D2V7uvI_1JD
"""

# 📦 Importing Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pickle

from google.colab import files
uploaded = files.upload()

# 📊 Load and Display Dataset
df = pd.read_csv('fraud_data.csv')
print("Dataset Loaded Successfully")
df.head()

# 🔧 Encode Categorical Features
df_encoded = pd.get_dummies(df, columns=['transaction_type', 'location'], drop_first=True)

# 🎯 Feature Selection
X = df_encoded.drop(['transaction_id', 'is_fraud'], axis=1)
y = df_encoded['is_fraud']

# 📤 Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 🧠 Train Random Forest Model
model = RandomForestClassifier()
model.fit(X_train, y_train)
print("Model Training Complete")

# 📈 Evaluate the Model
y_pred = model.predict(X_test)

print("📌 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\n📌 Classification Report:")
print(classification_report(y_test, y_pred))

# 💾 Save the Model
with open('fraud_detection_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("✅ Model saved as 'fraud_detection_model.pkl'")

from google.colab import files
files.download('fraud_detection_model.pkl')